### ISSUE TITLE
Cannot handle multiple before_actions on same line

### ISSUE THREAD

**Issue by m1foley** [tcopeland/filter_decrufter#2]
My project uses Rails 4.1. 

My controller:

```
class FooController < ApplicationController
  before_filter :filter1, :filter2
```

```
$ bundle exec rake filter_decrufter:check --trace
...
no implicit conversion of Symbol into Integer
.../.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/filter_decrufter-0.0.4/lib/filter_decrufter/checker.rb:95:in `[]'
.../.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/filter_decrufter-0.0.4/lib/filter_decrufter/checker.rb:95:in `block in patch_method'
.../app/controllers/foo_controller.rb:2:in `<class:FooController>'
```

**Comment by tcopeland** [comment]
Oops, thanks for the report @m1foley, working on it.  

While looking into this one I also found another issue that I fixed with  https://github.com/tcopeland/filter_decrufter/commit/5c79dc0d4b26c63dff079c9a98837f973764633c, so I hope to release 0.0.5 with both fixed soon.  I need to backfill some tests, too...

**Comment by tcopeland** [comment]
Fixed and 0.0.5 released, thanks again! 

Also, if you have a chance, if you can verify the fix I'll add Rails 4.1 to the list of tested versions.

**Comment by m1foley** [comment]
Verified it works in Rails 4.1. Thanks for the sweet tool!

**Comment by tcopeland** [comment]
Great, thanks @m1foley !
